name: cd

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restart server application
        run: |
          docker-compose down
          docker-compose up --build -d